const fs=require('fs'),path=require('path'),{spawn}=require('child_process');
class Agent{constructor({root,ollama,model,web,notify,permissions={}}){this.root=root;this.ollama=ollama;this.model=model;this.web=web;this.notify=notify||(()=>{});this.dir=path.join(root,'agent');fs.mkdirSync(this.dir,{recursive:true});this.file=path.join(this.dir,'state.json');this.state=this.load();this.running=false;this.permissions={web:true,files_read:true,files_write:false,code:false,documents:true,...permissions};}
load(){try{return JSON.parse(fs.readFileSync(this.file,'utf8'));}catch{return {tasks:[],knowledge:[],logs:[],schedules:[]};}}save(){fs.writeFileSync(this.file,JSON.stringify(this.state,null,2));}log(x){this.state.logs.push({at:new Date().toISOString(),text:x});this.state.logs=this.state.logs.slice(-1000);this.save();this.notify(x);}async ask(prompt){return this.ollama([{role:'system',content:'You are LocalMind autonomous agent. Be factual. Never bypass permissions. Return JSON when requested.'},{role:'user',content:prompt}]);}
async plan(goal){const raw=await this.ask(`Create an executable multi-step plan for: ${goal}. Available tools: web, files_read, files_write, code, documents. Respect permissions. Return JSON only {"steps":[{"title":string,"action":"web|files_read|files_write|code|documents|think","input":string}]}, max 12 steps.`);return JSON.parse(raw.replace(/```json|```/g,'').trim());}
async execute(goal){if(this.running)throw new Error('Агент уже выполняет задачу');this.running=true;try{this.log('Начинаю: '+goal);const plan=await this.plan(goal);const task={id:Date.now(),goal,steps:plan.steps,status:'running',createdAt:new Date().toISOString()};this.state.tasks.push(task);this.save();const evidence=[];for(let i=0;i<task.steps.length;i++){const s=task.steps[i];this.log(`Шаг ${i+1}/${task.steps.length}: ${s.title}`);if(s.action==='web'){if(!this.permissions.web)throw new Error('Нет разрешения web');evidence.push({step:s.title,result:(await this.web(s.input)||'').slice(0,12000)});}else if(s.action==='files_read'){if(!this.permissions.files_read)throw new Error('Нет разрешения files_read');evidence.push({step:s.title,result:this.readSafe(s.input)});}else if(s.action==='files_write'){if(!this.permissions.files_write)throw new Error('Нет разрешения files_write');this.writeSafe(s.input);evidence.push({step:s.title,result:'written'});}else if(s.action==='code'){if(!this.permissions.code)throw new Error('Нет разрешения code');evidence.push({step:s.title,result:await this.runSandbox(s.input)});}else if(s.action==='documents'){if(!this.permissions.documents)throw new Error('Нет разрешения documents');evidence.push({step:s.title,result:'document action approved'});}s.done=true;this.save();}
const synthesis=await this.ask(`Goal: ${goal}\nEvidence: ${JSON.stringify(evidence)}\nReturn JSON only {"answer":string,"facts":[string],"uncertainties":[string]}. Never invent facts.`);let out;try{out=JSON.parse(synthesis.replace(/```json|```/g,'').trim());}catch{out={answer:synthesis,facts:[],uncertainties:[]};}for(const f of(out.facts||[]))if(!this.state.knowledge.includes(f))this.state.knowledge.push(f);this.state.knowledge=this.state.knowledge.slice(-5000);task.status='completed';task.result=out;task.completedAt=new Date().toISOString();this.save();this.log('Задача завершена.');return out;}catch(e){this.log('Ошибка: '+e.message);throw e;}finally{this.running=false;}}
readSafe(p){const target=path.resolve(this.root,p);if(!target.startsWith(path.resolve(this.root)))throw new Error('Недопустимый путь');return fs.readFileSync(target,'utf8').slice(0,100000);}
writeSafe(input){const x=typeof input==='string'?JSON.parse(input):input;const target=path.resolve(this.root,x.path);if(!target.startsWith(path.resolve(this.root)))throw new Error('Недопустимый путь');fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,String(x.content||''));}
runSandbox(code){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,['-e',code],{cwd:this.dir,windowsHide:true,timeout:10000,stdio:['ignore','pipe','pipe']});let out='',err='';child.stdout.on('data',d=>out+=d);child.stderr.on('data',d=>err+=d);child.on('error',reject);child.on('close',c=>c===0?resolve(out.slice(0,20000)):reject(new Error(err||`code exit ${c}`)));});}
createTask(goal,when,repeat=null){const task={id:Date.now(),goal,status:'scheduled',when,repeat,createdAt:new Date().toISOString()};this.state.tasks.push(task);this.save();return task;}list(){return this.state.tasks.slice(-100).reverse();}knowledgeList(){return this.state.knowledge.slice(-200).reverse();}setPermissions(p){this.permissions={...this.permissions,...p};this.state.permissions=this.permissions;this.save();return this.permissions;}async tick(){const now=Date.now();for(const t of this.state.tasks.filter(x=>x.status==='scheduled')){if(new Date(t.when).getTime()>now)continue;try{t.status='running';this.save();await this.execute(t.goal);t.status='completed';if(t.repeat){const n=new Date(t.when);if(t.repeat==='hourly')n.setHours(n.getHours()+1);if(t.repeat==='daily')n.setDate(n.getDate()+1);if(t.repeat==='weekly')n.setDate(n.getDate()+7);t.when=n.toISOString();t.status='scheduled';}this.save();}catch(e){t.status='error';t.error=e.message;this.save();}}}}
module.exports=Agent;
